[project]
name = "blog-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sachin", email = "skpkorba9009@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = [
    "djlint>=1.44.2",
    "ruff>=0.16.4",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 80
indent-width = 4
target-version = "py314"

[tool.ruff.lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort (import sorting)
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "UP",     # pyupgrade (modern python syntax)
    "ARG",    # flake8-unused-arguments
    "SIM",    # flake8-simplify
    "FAST",   # FastAPI specific rules
]
ignore = [
    "B008",   # Do not perform function calls in argument defaults (essential for FastAPI Depends, Query, etc.)
]
unfixable = [
    "F401",   # Unused imports (prevent deleting imports on save/autofix)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

